// Copyright 2014-2017 Emilie Gillet.
//
// Author: Emilie Gillet (emilie.o.gillet@gmail.com)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
// 
// See http://creativecommons.org/licenses/MIT/ for more information.
//

// Generated by translate.py; C99 adaptation for the machine lab, 2026.
#include "core.h"
#include "pitch_tables.h"
static float maxf(float a, float b) { return a > b ? a : b; }
static float minf(float a, float b) { return a < b ? a : b; }
static float absf(float a) { return a < 0.0f ? -a : a; }
#define CONSTRAIN(v, lo, hi) if (v < (lo)) { v = (lo); } else if (v > (hi)) { v = (hi); }
#define MAKE_INTEGRAL_FRACTIONAL(v) int v##_integral = (int)v; float v##_fractional = v - (float)v##_integral;
typedef struct { float *state; float value; float increment; } Interp;
static Interp interp(float *s, float target, int size) {
  Interp p; p.state=s; p.value=*s; p.increment=(target-*s)/(float)size; return p;
}
static float next(Interp *p) { p->value += p->increment; return p->value; }
static void commit(Interp *p) { *p->state = p->value; }
static float ratio(float semitones) {
  float pitch=semitones+128.0f;
  MAKE_INTEGRAL_FRACTIONAL(pitch)
  return lut_pitch_ratio_high[pitch_integral] * lut_pitch_ratio_low[(int)(pitch_fractional*256.0f)];
}
static float NoteToFrequency(float note) {
  note -= 9.0f; CONSTRAIN(note,-128.0f,127.0f);
  return ((440.0f/8.0f)/47872.34f)*0.25f*ratio(note);
}
static const float kMaxFrequency=0.25f;
static const float kVariableSawNotchDepth=0.2f;

static float ThisBlepSample(float t) {
  return 0.5f * t * t;
}

static float NextBlepSample(float t) {
  t = 1.0f - t;
  return -0.5f * t * t;
}

static float NextIntegratedBlepSample(float t) {
  const float t1 = 0.5f * t;
  const float t2 = t1 * t1;
  const float t4 = t2 * t2;
  return 0.1875f - t1 + 1.5f * t2 - t4;
}

static float ThisIntegratedBlepSample(float t) {
  return NextIntegratedBlepSample(1.0f - t);
}

static void shape_init(Shape *s) {
    s->master_phase_ = 0.0f;
    s->slave_phase_ = 0.0f;
    s->next_sample_ = 0.0f;
    s->previous_pw_ = 0.5f;
    s->high_ = 0;
  
    s->master_frequency_ = 0.0f;
    s->slave_frequency_ = 0.01f;
    s->pw_ = 0.5f;
    s->waveshape_ = 0.0f;
    s->phase_modulation_ = 0.0f;
  
}

static float shape_naive(float phase, float pw, float slope_up, float slope_down, float triangle_amount, float square_amount) {
    float saw = phase;
    float square = phase < pw ? 0.0f : 1.0f;
    float triangle = phase < pw
        ? phase * slope_up
        : 1.0f - (phase - pw) * slope_down;
    saw += (square - saw) * square_amount;
    saw += (triangle - saw) * triangle_amount;
    return saw;
  
}

static void shape_render(Shape *s, float master_frequency, float frequency, float pw, float waveshape, float *out, int size) {const int enable_sync=1, output_phase=0; const float phase_modulation_amount=0.0f;

    if (master_frequency >= kMaxFrequency) {
      master_frequency = kMaxFrequency;
    }
    if (frequency >= kMaxFrequency) {
      frequency = kMaxFrequency;
    }
    
    if (frequency >= 0.25f) {
      pw = 0.5f;
    } else {
      CONSTRAIN(pw, frequency * 2.0f, 1.0f - 2.0f * frequency);
    }
    
    Interp master_fm = interp(
        &s->master_frequency_, master_frequency, size);
    Interp fm = interp(&s->slave_frequency_, frequency, size);
    Interp pwm = interp(&s->pw_, pw, size);
    Interp waveshape_modulation = interp(
        &s->waveshape_, waveshape, size);
    Interp phase_modulation = interp(
        &s->phase_modulation_, phase_modulation_amount, size);

    float next_sample = s->next_sample_;
    
    while (size--) {
      int reset = 0;
      int transition_during_reset = 0;
      float reset_time = 0.0f;

      float this_sample = next_sample;
      next_sample = 0.0f;
    
      const float master_frequency = next(&master_fm);
      const float slave_frequency = next(&fm);
      const float pw = next(&pwm);
      const float waveshape = next(&waveshape_modulation);
      
      const float square_amount = maxf(waveshape - 0.5f, 0.0f) * 2.0f;
      const float triangle_amount = maxf(1.0f - waveshape * 2.0f, 0.0f);
      
      const float slope_up = 1.0f / (pw);
      const float slope_down = 1.0f / (1.0f - pw);

      if (enable_sync) {
        s->master_phase_ += master_frequency;
        if (s->master_phase_ >= 1.0f) {
          s->master_phase_ -= 1.0f;
          reset_time = s->master_phase_ / master_frequency;
      
          float slave_phase_at_reset = s->slave_phase_ + \
              (1.0f - reset_time) * slave_frequency;
          reset = 1;
          if (slave_phase_at_reset >= 1.0f) {
            slave_phase_at_reset -= 1.0f;
            transition_during_reset = 1;
          }
          if (!s->high_ && slave_phase_at_reset >= pw) {
            transition_during_reset = 1;
          }
          float value = shape_naive(
              slave_phase_at_reset,
              pw,
              slope_up,
              slope_down,
              triangle_amount,
              square_amount);
          this_sample -= value * ThisBlepSample(reset_time);
          next_sample -= value * NextBlepSample(reset_time);
        }
      } else if (output_phase) {
        s->master_phase_ += master_frequency;
        if (s->master_phase_ >= 1.0f) {
          s->master_phase_ -= 1.0f;
        }
      }
      
      s->slave_phase_ += slave_frequency;
      while (transition_during_reset || !reset) {
        if (!s->high_) {
          if (s->slave_phase_ < pw) {
            break;
          }
          float t = (s->slave_phase_ - pw) / (s->previous_pw_ - pw + slave_frequency);
          float triangle_step = (slope_up + slope_down) * slave_frequency;
          triangle_step *= triangle_amount;
          
          this_sample += square_amount * ThisBlepSample(t);
          next_sample += square_amount * NextBlepSample(t);
          this_sample -= triangle_step * ThisIntegratedBlepSample(t);
          next_sample -= triangle_step * NextIntegratedBlepSample(t);
          s->high_ = 1;
        }
      
        if (s->high_) {
          if (s->slave_phase_ < 1.0f) {
            break;
          }
          s->slave_phase_ -= 1.0f;
          float t = s->slave_phase_ / slave_frequency;
          float triangle_step = (slope_up + slope_down) * slave_frequency;
          triangle_step *= triangle_amount;

          this_sample -= (1.0f - triangle_amount) * ThisBlepSample(t);
          next_sample -= (1.0f - triangle_amount) * NextBlepSample(t);
          this_sample += triangle_step * ThisIntegratedBlepSample(t);
          next_sample += triangle_step * NextIntegratedBlepSample(t);
          s->high_ = 0;
        }
      }
    
      if (enable_sync && reset) {
        s->slave_phase_ = reset_time * slave_frequency;
        s->high_ = 0;
      }
    
      next_sample += shape_naive(
          s->slave_phase_,
          pw,
          slope_up,
          slope_down,
          triangle_amount,
          square_amount);
      s->previous_pw_ = pw;
      
      if (output_phase) {
        float phasor = s->master_phase_;
        if (enable_sync) {
          // A trick to prevent discontinuities when the phase wraps around.
          const float w = 4.0f * (1.0f - s->master_phase_) * s->master_phase_;
          this_sample *= w * (2.0f - w);
          
          // Apply some asymmetry on the main phasor too.
          const float p2 = phasor * phasor;
          phasor += (p2 * p2 - phasor) * absf(pw - 0.5f) * 2.0f;
        }
        *out++ = phasor + next(&phase_modulation) * this_sample;
      } else {
        *out++ = (2.0f * this_sample - 1.0f);
      }
    }
    
    s->next_sample_ = next_sample;
  
commit(&master_fm);
commit(&fm);
commit(&pwm);
commit(&waveshape_modulation);
commit(&phase_modulation);}

static void saw_init(Saw *s) {
    s->phase_ = 0.0f;
    s->next_sample_ = 0.0f;
    s->previous_pw_ = 0.5f;
    s->high_ = 0;
  
    s->frequency_ = 0.01f;
    s->pw_ = 0.5f;
    s->waveshape_ = 0.0f;
  
}

static float saw_naive(float phase, float pw, float slope_up, float slope_down, float triangle_amount, float notch_amount) {
    float notch_saw = phase < pw ? phase : 1.0f + kVariableSawNotchDepth;
    float triangle = phase < pw
        ? phase * slope_up
        : 1.0f - (phase - pw) * slope_down;
    return notch_saw * notch_amount + triangle * triangle_amount;
  
}

static void saw_render(Saw *s, float frequency, float pw, float waveshape, float *out, int size) {
    if (frequency >= kMaxFrequency) {
      frequency = kMaxFrequency;
    }
    
    if (frequency >= 0.25f) {
      pw = 0.5f;
    } else {
      CONSTRAIN(pw, frequency * 2.0f, 1.0f - 2.0f * frequency);
    }

    Interp fm = interp(&s->frequency_, frequency, size);
    Interp pwm = interp(&s->pw_, pw, size);
    Interp waveshape_modulation = interp(
        &s->waveshape_, waveshape, size);

    float next_sample = s->next_sample_;
    
    while (size--) {
      float this_sample = next_sample;
      next_sample = 0.0f;
    
      const float frequency = next(&fm);
      const float pw = next(&pwm);
      const float waveshape = next(&waveshape_modulation);
      const float triangle_amount = waveshape;
      const float notch_amount = 1.0f - waveshape;
      const float slope_up = 1.0f / (pw);
      const float slope_down = 1.0f / (1.0f - pw);

      s->phase_ += frequency;
      
      if (!s->high_ && s->phase_ >= pw) {
        const float triangle_step = (slope_up + slope_down) * frequency * triangle_amount;
        const float notch = (kVariableSawNotchDepth + 1.0f - pw) * notch_amount;
        const float t = (s->phase_ - pw) / (s->previous_pw_ - pw + frequency);
        this_sample += notch * ThisBlepSample(t);
        next_sample += notch * NextBlepSample(t);
        this_sample -= triangle_step * ThisIntegratedBlepSample(t);
        next_sample -= triangle_step * NextIntegratedBlepSample(t);
        s->high_ = 1;
      } else if (s->phase_ >= 1.0f) {
        s->phase_ -= 1.0f;
        const float triangle_step = (slope_up + slope_down) * frequency * triangle_amount;
        const float notch = (kVariableSawNotchDepth + 1.0f) * notch_amount;
        const float t = s->phase_ / frequency;
        this_sample -= notch * ThisBlepSample(t);
        next_sample -= notch * NextBlepSample(t);
        this_sample += triangle_step * ThisIntegratedBlepSample(t);
        next_sample += triangle_step * NextIntegratedBlepSample(t);
        s->high_ = 0;
      }
    
      next_sample += saw_naive(
          s->phase_,
          pw,
          slope_up,
          slope_down,
          triangle_amount,
          notch_amount);
      s->previous_pw_ = pw;

      *out++ = (2.0f * this_sample - 1.0f) / (1.0f + kVariableSawNotchDepth);
    }
    
    s->next_sample_ = next_sample;
  
commit(&fm);
commit(&pwm);
commit(&waveshape_modulation);}

static const float intervals[5]={0.0f,7.01f,12.01f,19.01f,24.01f};

static float Squash(float x) {
  return x * x * (3.0f - 2.0f * x);
}

static float ComputeDetuning(float detune) {
  detune = 2.05f * detune - 1.025f;
  CONSTRAIN(detune, -1.0f, 1.0f);
  
  float sign = detune < 0.0f ? -1.0f : 1.0f;
  detune = detune * sign * 3.9999f;
  MAKE_INTEGRAL_FRACTIONAL(detune);
  
  float a = intervals[detune_integral];
  float b = intervals[detune_integral + 1];
  return (a + (b - a) * Squash(Squash(detune_fractional))) * sign;

}

void va_init(VA *s) {
  shape_init(&s->primary_); shape_init(&s->auxiliary_);
  s->auxiliary_.master_phase_=0.25f;
  shape_init(&s->sync_); saw_init(&s->variable_saw_);
  s->auxiliary_amount_=0.0f; s->xmod_amount_=0.0f;
}

void va_render(VA *s, const Params *p, float *out, float *aux, int size) {

  // 1 = variable square controlled by TIMBRE.
  // 2 = variable saw controlled by MORPH.
  // OUT = 1 + 2.
  // AUX = dual variable waveshape controlled by MORPH, self sync by TIMBRE.
  
  const float sync_amount = p->timbre * p->timbre;
  const float auxiliary_detune = ComputeDetuning(p->harmonics);
  const float primary_f = NoteToFrequency(p->note);
  const float auxiliary_f = NoteToFrequency(p->note + auxiliary_detune);
  const float primary_sync_f = NoteToFrequency(
      p->note + sync_amount * 48.0f);
  const float auxiliary_sync_f = NoteToFrequency(
      p->note + auxiliary_detune + sync_amount * 48.0f);

  float shape = p->morph * 1.5f;
  CONSTRAIN(shape, 0.0f, 1.0f);

  float pw = 0.5f + (p->morph - 0.66f) * 1.46f;
  CONSTRAIN(pw, 0.5f, 0.995f);
  
  // Render monster sync to AUX.
  shape_render(&s->primary_, primary_f, primary_sync_f, pw, shape, out, size);
  shape_render(&s->auxiliary_, auxiliary_f, auxiliary_sync_f, pw, shape, aux, size);
  for (int i = 0; i < size; ++i) {
    aux[i] = (aux[i] - out[i]) * 0.5f;
  }
  
  // Render double varishape to OUT.
  float square_pw = 1.3f * p->timbre - 0.15f;
  CONSTRAIN(square_pw, 0.005f, 0.5f);
  
  const float square_sync_ratio = p->timbre < 0.5f
      ? 0.0f
      : (p->timbre - 0.5f) * (p->timbre - 0.5f) * 4.0f * 48.0f;
  
  const float square_gain = minf(p->timbre * 8.0f, 1.0f);
  
  float saw_pw = p->morph < 0.5f
      ? p->morph + 0.5f
      : 1.0f - (p->morph - 0.5f) * 2.0f;
  saw_pw *= 1.1f;
  CONSTRAIN(saw_pw, 0.005f, 1.0f);
    
  float saw_shape = 10.0f - 21.0f * p->morph;
  CONSTRAIN(saw_shape, 0.0f, 1.0f);
  
  float saw_gain = 8.0f * (1.0f - p->morph);
  CONSTRAIN(saw_gain, 0.02f, 1.0f);
  
  const float square_sync_f = NoteToFrequency(
      p->note + square_sync_ratio);
  
  shape_render(&s->sync_, 
      primary_f, square_sync_f, square_pw, 1.0f, s->temp_buffer_, size);
  saw_render(&s->variable_saw_, auxiliary_f, saw_pw, saw_shape, out, size);
  
  float norm = 1.0f / (maxf(square_gain, saw_gain));
  
  Interp square_gain_modulation = interp(
      &s->auxiliary_amount_,
      square_gain * 0.3f * norm,
      size);

  Interp saw_gain_modulation = interp(
      &s->xmod_amount_,
      saw_gain * 0.5f * norm,
      size);
  
  for (int i = 0; i < size; ++i) {
    out[i] = out[i] * next(&saw_gain_modulation) + \
        next(&square_gain_modulation) * s->temp_buffer_[i];
  }


commit(&square_gain_modulation);
commit(&saw_gain_modulation);}
