"""Reproducible, deliberately narrow C99 translation of pinned Plaits VA2.

The source files remain the authority. This removes C++ object/RAII syntax;
it does not approximate oscillators or regenerate upstream lookup values.
"""

import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
source = Path(sys.argv[1]).resolve()
lock = json.loads((HERE / "source-lock.json").read_text())
for name, digest in lock["files"].items():
    if hashlib.sha256((source / name).read_bytes()).hexdigest() != digest:
        raise ValueError(f"Source hash mismatch: {name}")


def read(name):
    return (source / name).read_text()


def body(text, signature):
    start = text.index("{", text.index(signature)) + 1
    depth, end = 1, start
    while depth:
        depth += (text[end] == "{") - (text[end] == "}")
        end += 1
    return text[start : end - 1]


notice = read("plaits/dsp/engine/virtual_analog_engine.cc").split("// ---")[0]
notice = notice.replace("Copyright 2016", "Copyright 2014-2017")
preamble = (
    notice
    + """
// Generated by translate.py; C99 adaptation for the machine lab, 2026.
#include "core.h"
#include "pitch_tables.h"
static float maxf(float a, float b) { return a > b ? a : b; }
static float minf(float a, float b) { return a < b ? a : b; }
static float absf(float a) { return a < 0.0f ? -a : a; }
#define CONSTRAIN(v, lo, hi) if (v < (lo)) { v = (lo); } else if (v > (hi)) { v = (hi); }
#define MAKE_INTEGRAL_FRACTIONAL(v) int v##_integral = (int)v; float v##_fractional = v - (float)v##_integral;
typedef struct { float *state; float value; float increment; } Interp;
static Interp interp(float *s, float target, int size) {
  Interp p; p.state=s; p.value=*s; p.increment=(target-*s)/(float)size; return p;
}
static float next(Interp *p) { p->value += p->increment; return p->value; }
static void commit(Interp *p) { *p->state = p->value; }
static float ratio(float semitones) {
  float pitch=semitones+128.0f;
  MAKE_INTEGRAL_FRACTIONAL(pitch)
  return lut_pitch_ratio_high[pitch_integral] * lut_pitch_ratio_low[(int)(pitch_fractional*256.0f)];
}
static float NoteToFrequency(float note) {
  note -= 9.0f; CONSTRAIN(note,-128.0f,127.0f);
  return ((440.0f/8.0f)/47872.34f)*0.25f*ratio(note);
}
static const float kMaxFrequency=0.25f;
static const float kVariableSawNotchDepth=0.2f;
"""
)


def common(text):
    text = text.replace("stmlib::", "").replace("std::", "")
    text = re.sub(r"\bmax\(", "maxf(", text)
    text = re.sub(r"\bmin\(", "minf(", text).replace("fabsf(", "absf(")
    for old, new in [("bool", "int"), ("true", "1"), ("false", "0"), ("size_t", "int")]:
        text = re.sub(r"\b" + old + r"\b", new, text)
    text = re.sub(r"\b([a-zA-Z]\w*_)\b", r"s->\1", text)
    names = re.findall(r"ParameterInterpolator\s+(\w+)\(", text)
    text = re.sub(r"ParameterInterpolator\s+(\w+)\(", r"Interp \1 = interp(", text)
    text = re.sub(r"(\w+)\.Next\(\)", r"next(&\1)", text)
    return text + "\n" + "\n".join(f"commit(&{n});" for n in names)


parts = [preamble]
blep = read("stmlib/dsp/polyblep.h")
for name in [
    "ThisBlepSample",
    "NextBlepSample",
    "NextIntegratedBlepSample",
    "ThisIntegratedBlepSample",
]:
    parts.append(
        f"static float {name}(float t) {{" + body(blep, f"float {name}(") + "}\n"
    )
for kind, typ in [("shape", "Shape"), ("saw", "Saw")]:
    text = read(f"plaits/dsp/oscillator/variable_{kind}_oscillator.h")
    parts.append(
        f"static void {kind}_init({typ} *s) {{"
        + common(body(text, "void Init()"))
        + "}\n"
    )
    signature = "float phase, float pw, float slope_up, float slope_down, float triangle_amount, float "
    signature += "square_amount" if kind == "shape" else "notch_amount"
    parts.append(
        f"static float {kind}_naive({signature}) {{"
        + common(body(text, "float ComputeNaiveSample("))
        + "}\n"
    )
    if kind == "shape":
        sig = "Shape *s, float master_frequency, float frequency, float pw, float waveshape, float *out, int size"
        prefix = "const int enable_sync=1, output_phase=0; const float phase_modulation_amount=0.0f;\n"
        render = body(text[text.index("template<bool enable_sync") :], "void Render(")
    else:
        sig = "Saw *s, float frequency, float pw, float waveshape, float *out, int size"
        prefix = ""
        render = body(text, "void Render(")
    parts.append(
        f"static void {kind}_render({sig}) {{"
        + prefix
        + common(render).replace("ComputeNaiveSample(", f"{kind}_naive(")
        + "}\n"
    )

engine = read("plaits/dsp/engine/virtual_analog_engine.cc")
parts.append("static const float intervals[5]={0.0f,7.01f,12.01f,19.01f,24.01f};\n")
parts.append("static float Squash(float x) {" + body(engine, "float Squash(") + "}\n")
parts.append(
    "static float ComputeDetuning(float detune) {"
    + common(body(engine, "float VirtualAnalogEngine::ComputeDetuning("))
    + "}\n"
)
parts.append("""void va_init(VA *s) {
  shape_init(&s->primary_); shape_init(&s->auxiliary_);
  s->auxiliary_.master_phase_=0.25f;
  shape_init(&s->sync_); saw_init(&s->variable_saw_);
  s->auxiliary_amount_=0.0f; s->xmod_amount_=0.0f;
}
""")
render = engine.split("#elif VA_VARIANT == 2")[1].split("#endif")[0]
render = common(render).replace("parameters.", "p->")
for name in ["primary_", "auxiliary_", "sync_"]:
    render = render.replace(f"s->{name}.Render(", f"shape_render(&s->{name}, ")
render = render.replace("s->variable_saw_.Render(", "saw_render(&s->variable_saw_, ")
# The firmware consumes MAIN only. Retain the original by default, and guard
# only AUX-exclusive calculations/state updates in the optional specialization.
sync = "  const float sync_amount = p->timbre * p->timbre;"
if render.count(sync) != 1:
    raise ValueError("Expected one AUX sync calculation")
render = render.replace(sync, "#ifndef PLAITS_MAIN_ONLY\n" + sync + "\n#endif")
aux_start = "  const float primary_sync_f = NoteToFrequency("
aux_end = "  // Render double varishape to OUT."
if render.count(aux_start) != 1 or render.count(aux_end) != 1:
    raise ValueError("Expected one bounded AUX render region")
render = render.replace(aux_start, "#ifndef PLAITS_MAIN_ONLY\n" + aux_start)
render = render.replace(aux_end, "#endif\n" + aux_end)
parts.append(
    "void va_render(VA *s, const Params *p, float *out, float *aux, int size) {"
    + render
    + "}\n"
)
(HERE / "core.c").write_text("\n".join(parts))
tables = read("stmlib/dsp/units.cc")
tables = tables.split("namespace stmlib {")[1].rsplit("}", 1)[0]
(HERE / "pitch_tables.h").write_text(
    notice + "// Original upstream pitch table constants.\n" + tables
)
(HERE / "core.h").write_text(
    notice
    + """
#ifndef DT2_PLAITS_VA_H
#define DT2_PLAITS_VA_H
typedef struct {
 float master_phase_,slave_phase_,next_sample_,previous_pw_; int high_;
 float master_frequency_,slave_frequency_,pw_,waveshape_,phase_modulation_;
} Shape;
typedef struct {
 float phase_,next_sample_,previous_pw_; int high_;
 float frequency_,pw_,waveshape_;
} Saw;
typedef struct {
 Shape primary_,auxiliary_,sync_; Saw variable_saw_;
 float auxiliary_amount_,xmod_amount_,temp_buffer_[24];
} VA;
typedef struct { float note,harmonics,timbre,morph; } Params;
#ifdef __cplusplus
extern "C" {
#endif
void va_init(VA *s);
void va_render(VA *s,const Params *p,float *out,float *aux,int size);
#ifdef __cplusplus
}
#endif
#endif
"""
)
print("Pinned hashes match; generated core.c, core.h and original pitch tables.")
